package projecteuler.kotlin

/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
class Problem2 {

    companion object {

        @JvmStatic
        fun main(args: Array<String>) {

            val list = mutableListOf<Int>(1, 2)

            var i = 2
            while (i < 4000000) {
                val j = list[i - 1] + list[i - 2]

                list.add(j)

                i++
            }

            println("sum: ${list.evens().sum()}")

        }
    }
}